# Generated by Django 4.0 on 2023-02-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_alter_frmdevice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='frmdevice',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='frmdevice',
            name='type',
            field=models.CharField(choices=[('MOTION', 'MOTION'), ('POWER', 'POWER'), ('STATION', 'STATION')], max_length=50),
        ),
    ]
