# Generated by Django 4.0 on 2023-02-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0006_alter_frmdevice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frmdevice',
            name='type',
            field=models.CharField(choices=[('POWER', 'POWER'), ('STATION', 'STATION'), ('MOTION', 'MOTION')], max_length=50),
        ),
    ]
