# Generated by Django 4.0 on 2023-02-19 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0007_alter_frmdevice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frmdevice',
            name='type',
            field=models.CharField(choices=[('MOTION', 'MOTION'), ('POWER', 'POWER'), ('STATION', 'STATION')], max_length=50),
        ),
    ]
