# Generated by Django 4.0 on 2023-02-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0009_alter_frmdevice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='frmdevice',
            name='attahment',
            field=models.PositiveIntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='frmdevice',
            name='type',
            field=models.CharField(choices=[('MOTION', 'MOTION'), ('STATION', 'STATION'), ('CONTROL', 'CONTROL')], max_length=50),
        ),
    ]
