# Generated by Django 4.0 on 2023-03-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0018_alter_frmdevice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frmdevice',
            name='type',
            field=models.CharField(choices=[('STATION', 'STATION'), ('MOTION', 'MOTION'), ('CONTROL', 'CONTROL')], max_length=50),
        ),
    ]
