# Generated by Django 4.0 on 2023-02-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_rename_reading_devrecord_amp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devrecord',
            old_name='amp',
            new_name='amp_0',
        ),
        migrations.RenameField(
            model_name='devrecord',
            old_name='button',
            new_name='button_0',
        ),
        migrations.AddField(
            model_name='devrecord',
            name='amp_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devrecord',
            name='amp_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devrecord',
            name='amp_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devrecord',
            name='amp_4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devrecord',
            name='amp_5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devrecord',
            name='amp_6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devrecord',
            name='amp_7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devrecord',
            name='amp_8',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devrecord',
            name='amp_9',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devrecord',
            name='button_1',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devrecord',
            name='button_2',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devrecord',
            name='button_3',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devrecord',
            name='button_4',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devrecord',
            name='button_5',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devrecord',
            name='button_6',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devrecord',
            name='button_7',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devrecord',
            name='button_8',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devrecord',
            name='button_9',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
