# Generated by Django 4.0 on 2023-02-01 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0006_alter_frmdevice_type'),
        ('record', '0004_devrecord_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devrecord',
            name='button_0',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devrecord',
            name='button_1',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devrecord',
            name='button_2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devrecord',
            name='button_3',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devrecord',
            name='button_4',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devrecord',
            name='button_5',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devrecord',
            name='button_6',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devrecord',
            name='button_7',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devrecord',
            name='button_8',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devrecord',
            name='button_9',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devrecord',
            name='motion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PwrAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_0', models.PositiveIntegerField(blank=True, null=True)),
                ('button_1', models.PositiveIntegerField(blank=True, null=True)),
                ('button_2', models.PositiveIntegerField(blank=True, null=True)),
                ('button_3', models.PositiveIntegerField(blank=True, null=True)),
                ('button_4', models.PositiveIntegerField(blank=True, null=True)),
                ('button_5', models.PositiveIntegerField(blank=True, null=True)),
                ('button_6', models.PositiveIntegerField(blank=True, null=True)),
                ('button_7', models.PositiveIntegerField(blank=True, null=True)),
                ('button_8', models.PositiveIntegerField(blank=True, null=True)),
                ('button_9', models.PositiveIntegerField(blank=True, null=True)),
                ('motion', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farms.frmdevice')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.frmprofile')),
            ],
        ),
    ]
