# Generated by Django 4.0 on 2023-02-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_alter_devrecord_button_0_alter_devrecord_button_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwraction',
            name='button_0',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='pwraction',
            name='button_1',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='pwraction',
            name='button_2',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='pwraction',
            name='button_3',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='pwraction',
            name='button_4',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='pwraction',
            name='button_5',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='pwraction',
            name='button_6',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='pwraction',
            name='button_7',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='pwraction',
            name='button_8',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='pwraction',
            name='button_9',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='pwraction',
            name='motion',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
    ]
