# Generated by Django 4.0 on 2023-02-19 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0008_alter_frmdevice_type'),
        ('record', '0006_alter_pwraction_button_0_alter_pwraction_button_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DvcUpdte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updte', models.BooleanField(default=False)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farms.frmdevice')),
            ],
        ),
    ]
