# Generated by Django 4.0 on 2023-02-20 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0010_frmdevice_attahment_alter_frmdevice_type'),
        ('record', '0008_dvcupdte_farm_alter_dvcupdte_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='BtnRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btn_0', models.PositiveIntegerField(blank=True, default='0', null=True)),
                ('btn_1', models.PositiveIntegerField(blank=True, default='0', null=True)),
                ('btn_2', models.PositiveIntegerField(blank=True, default='0', null=True)),
                ('btn_3', models.PositiveIntegerField(blank=True, default='0', null=True)),
                ('btn_4', models.PositiveIntegerField(blank=True, default='0', null=True)),
                ('btn_5', models.PositiveIntegerField(blank=True, default='0', null=True)),
                ('btn_6', models.PositiveIntegerField(blank=True, default='0', null=True)),
                ('btn_7', models.PositiveIntegerField(blank=True, default='0', null=True)),
                ('btn_8', models.PositiveIntegerField(blank=True, default='0', null=True)),
                ('btn_9', models.PositiveIntegerField(blank=True, default='0', null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.frmdevice')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('re_name', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(max_length=50)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.frmdevice')),
            ],
        ),
        migrations.RenameField(
            model_name='devrecord',
            old_name='amp_0',
            new_name='sensor_1',
        ),
        migrations.RenameField(
            model_name='devrecord',
            old_name='amp_1',
            new_name='sensor_10',
        ),
        migrations.RenameField(
            model_name='devrecord',
            old_name='amp_2',
            new_name='sensor_11',
        ),
        migrations.RenameField(
            model_name='devrecord',
            old_name='amp_3',
            new_name='sensor_12',
        ),
        migrations.RenameField(
            model_name='devrecord',
            old_name='amp_4',
            new_name='sensor_2',
        ),
        migrations.RenameField(
            model_name='devrecord',
            old_name='amp_5',
            new_name='sensor_3',
        ),
        migrations.RenameField(
            model_name='devrecord',
            old_name='amp_6',
            new_name='sensor_4',
        ),
        migrations.RenameField(
            model_name='devrecord',
            old_name='amp_7',
            new_name='sensor_5',
        ),
        migrations.RenameField(
            model_name='devrecord',
            old_name='amp_8',
            new_name='sensor_6',
        ),
        migrations.RenameField(
            model_name='devrecord',
            old_name='amp_9',
            new_name='sensor_8',
        ),
        migrations.RenameField(
            model_name='devrecord',
            old_name='humd',
            new_name='sensor_9',
        ),
        migrations.RenameField(
            model_name='pwraction',
            old_name='button_0',
            new_name='btn_0',
        ),
        migrations.RenameField(
            model_name='pwraction',
            old_name='button_1',
            new_name='btn_1',
        ),
        migrations.RenameField(
            model_name='pwraction',
            old_name='button_2',
            new_name='btn_2',
        ),
        migrations.RenameField(
            model_name='pwraction',
            old_name='button_3',
            new_name='btn_3',
        ),
        migrations.RenameField(
            model_name='pwraction',
            old_name='button_4',
            new_name='btn_4',
        ),
        migrations.RenameField(
            model_name='pwraction',
            old_name='button_5',
            new_name='btn_5',
        ),
        migrations.RenameField(
            model_name='pwraction',
            old_name='button_6',
            new_name='btn_6',
        ),
        migrations.RenameField(
            model_name='pwraction',
            old_name='button_7',
            new_name='btn_7',
        ),
        migrations.RenameField(
            model_name='pwraction',
            old_name='button_8',
            new_name='btn_8',
        ),
        migrations.RenameField(
            model_name='pwraction',
            old_name='button_9',
            new_name='btn_9',
        ),
        migrations.RemoveField(
            model_name='devrecord',
            name='button_0',
        ),
        migrations.RemoveField(
            model_name='devrecord',
            name='button_1',
        ),
        migrations.RemoveField(
            model_name='devrecord',
            name='button_2',
        ),
        migrations.RemoveField(
            model_name='devrecord',
            name='button_3',
        ),
        migrations.RemoveField(
            model_name='devrecord',
            name='button_4',
        ),
        migrations.RemoveField(
            model_name='devrecord',
            name='button_5',
        ),
        migrations.RemoveField(
            model_name='devrecord',
            name='button_6',
        ),
        migrations.RemoveField(
            model_name='devrecord',
            name='button_8',
        ),
        migrations.RemoveField(
            model_name='devrecord',
            name='button_9',
        ),
        migrations.RemoveField(
            model_name='devrecord',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='devrecord',
            name='light',
        ),
        migrations.RemoveField(
            model_name='devrecord',
            name='motion',
        ),
        migrations.RemoveField(
            model_name='devrecord',
            name='temp',
        ),
        migrations.RemoveField(
            model_name='devrecord',
            name='temp2',
        ),
        migrations.RemoveField(
            model_name='devrecord',
            name='type',
        ),
        migrations.RemoveField(
            model_name='pwraction',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='pwraction',
            name='motion',
        ),
        migrations.AddField(
            model_name='pwraction',
            name='updte',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='devrecord',
            name='button_7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DvcUpdte',
        ),
    ]
