# Generated by Django 4.0 on 2023-02-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0010_alter_pwraction_btn_0_alter_pwraction_btn_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwraction',
            name='btn_0',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pwraction',
            name='btn_1',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pwraction',
            name='btn_2',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pwraction',
            name='btn_3',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pwraction',
            name='btn_4',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pwraction',
            name='btn_5',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pwraction',
            name='btn_6',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pwraction',
            name='btn_7',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pwraction',
            name='btn_8',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pwraction',
            name='btn_9',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
