# Generated by Django 4.0 on 2023-02-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0012_rename_button_7_devrecord_sensor_7_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='btnrecord',
            name='crt_0',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='btnrecord',
            name='crt_1',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='btnrecord',
            name='crt_2',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='btnrecord',
            name='crt_3',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='btnrecord',
            name='crt_4',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='btnrecord',
            name='crt_5',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='btnrecord',
            name='crt_6',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='btnrecord',
            name='crt_7',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='btnrecord',
            name='crt_8',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='btnrecord',
            name='crt_9',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
    ]
