# Generated by Django 4.0 on 2023-02-24 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0015_alter_frmdevice_type'),
        ('record', '0013_btnrecord_crt_0_btnrecord_crt_1_btnrecord_crt_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PwrBtnNme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btn_0', models.CharField(blank=True, default='Power 1', max_length=50, null=True)),
                ('btn_1', models.CharField(blank=True, default='Power 2', max_length=50, null=True)),
                ('btn_2', models.CharField(blank=True, default='Power 3', max_length=50, null=True)),
                ('btn_3', models.CharField(blank=True, default='Power 4', max_length=50, null=True)),
                ('btn_4', models.CharField(blank=True, default='Power 5', max_length=50, null=True)),
                ('btn_5', models.CharField(blank=True, default='Power 6', max_length=50, null=True)),
                ('btn_6', models.CharField(blank=True, default='Power 7', max_length=50, null=True)),
                ('btn_7', models.CharField(blank=True, default='Power 8', max_length=50, null=True)),
                ('btn_8', models.CharField(blank=True, default='Power 9', max_length=50, null=True)),
                ('btn_9', models.CharField(blank=True, default='Power 10', max_length=50, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.frmdevice')),
            ],
        ),
    ]
