# Generated by Django 4.0 on 2023-02-24 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0016_alter_frmdevice_type'),
        ('record', '0014_pwrbtnnme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwrbtnnme',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farms.frmdevice'),
        ),
    ]
