# Generated by Django 4.0 on 2023-02-24 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0017_alter_frmdevice_type'),
        ('record', '0015_alter_pwrbtnnme_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='pwrbtnnme',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farms.frmprofile'),
        ),
    ]
