# Generated by Django 4.0 on 2023-03-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0017_devicesrules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesrules',
            name='rulstat',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
