# Generated by Django 4.0 on 2023-03-01 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0020_alter_frmdevice_type'),
        ('record', '0018_alter_devicesrules_rulstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesrules',
            name='cdevice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cdevice', to='farms.frmdevice'),
        ),
        migrations.AlterField(
            model_name='devicesrules',
            name='sdevice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdevice', to='farms.frmdevice'),
        ),
    ]
