# Generated by Django 4.0 on 2023-03-01 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0021_alter_frmdevice_type'),
        ('record', '0019_alter_devicesrules_cdevice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesrules',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farms.frmprofile'),
        ),
    ]
