# Generated by Django 4.0 on 2023-03-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0020_devicesrules_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesrules',
            name='btntxt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
