# Generated by Django 4.0 on 2023-03-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0021_devicesrules_btntxt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesrules',
            name='rulecond',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='devicesrules',
            name='snsorvlue',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
